/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import db.DBConnection;
import java.sql.Connection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class SalesForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SalesForm.class.getName());
    double totalAmount = 0;
    
    public SalesForm() {
        initComponents();
        loadProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbProducts = new javax.swing.JComboBox<>();
        txtQty = new javax.swing.JTextField();
        btnAddToCart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbProducts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProducts.addActionListener(this::cmbProductsActionPerformed);

        txtQty.addActionListener(this::txtQtyActionPerformed);

        btnAddToCart.setText("Add to cart");
        btnAddToCart.addActionListener(this::btnAddToCartActionPerformed);

        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id.", "Product", "Unit Price(Rs.)", "Quantity", "Subtotal(Rs.)"
            }
        ));
        jScrollPane1.setViewportView(tblCart);

        jLabel1.setText("Product List :");

        jLabel2.setText("Quantity :");

        jLabel3.setText("Cart : ");

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("SALES FORM");

        btnComplete.setText("Complete");
        btnComplete.addActionListener(this::btnCompleteActionPerformed);

        lblTotal.setText("Total");

        jLabel5.setText("Generated Bill");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(btnAddToCart)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(86, 86, 86))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTotal)
                                        .addGap(328, 328, 328))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(199, 199, 199)
                                        .addComponent(btnComplete))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(250, 250, 250))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addComponent(btnAddToCart)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComplete)
                    .addComponent(lblTotal))
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
         try {
        String selected = cmbProducts.getSelectedItem().toString();
        int qty = Integer.parseInt(txtQty.getText());

        String[] parts = selected.split(" - ");
        int productId = Integer.parseInt(parts[0]);
        String name = parts[1];
        double price = Double.parseDouble(parts[2].replace("Rs.",""));

        double subtotal = price * qty;
        totalAmount += subtotal;

        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        model.addRow(new Object[]{
            productId, name, price, qty, subtotal
        });

        lblTotal.setText("Total: Rs." + totalAmount);

        txtQty.setText("");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,"Invalid Input!");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnAddToCartActionPerformed

    private void cmbProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProductsActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
       Connection con = null;
    try {
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();

        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(this, "Cart is empty!");
            return;
        }

        con = DBConnection.getConnection();
        con.setAutoCommit(false);

        // Insert into sales table
        String saleSQL = "INSERT INTO sales(sale_date, user_id, total_amount) VALUES(NOW(), ?, ?)";
        PreparedStatement pstSale = con.prepareStatement(saleSQL, PreparedStatement.RETURN_GENERATED_KEYS);
        pstSale.setInt(1, 1); // logged user id
        pstSale.setDouble(2, totalAmount);
        pstSale.executeUpdate();

        ResultSet rs = pstSale.getGeneratedKeys();
        int saleId = 0;
        if (rs.next()) saleId = rs.getInt(1);

        StringBuilder bill = new StringBuilder();
        bill.append("------ BILL ------\n");

        // Loop through cart items
        for (int i = 0; i < model.getRowCount(); i++) {
            Object objProductId = model.getValueAt(i, 0);
            Object objName = model.getValueAt(i, 1);
            Object objPrice = model.getValueAt(i, 2);
            Object objQty = model.getValueAt(i, 3);
            Object objSubtotal = model.getValueAt(i, 4);

            if (objProductId == null || objQty == null || objPrice == null || objSubtotal == null) continue;

            int productId = Integer.parseInt(objProductId.toString());
            String name = objName.toString();
            int qty = Integer.parseInt(objQty.toString());
            double price = Double.parseDouble(objPrice.toString());
            double subtotal = Double.parseDouble(objSubtotal.toString());

            // Insert sale items
            String itemSQL = "INSERT INTO sale_items(sale_id, product_id, quantity, unit_price, subtotal) VALUES(?,?,?,?,?)";
            PreparedStatement pstItem = con.prepareStatement(itemSQL);
            pstItem.setInt(1, saleId);
            pstItem.setInt(2, productId);
            pstItem.setInt(3, qty);
            pstItem.setDouble(4, price);
            pstItem.setDouble(5, subtotal);
            pstItem.executeUpdate();

            // Reduce product quantity in DB
            String updateSQL = "UPDATE products SET quantity = quantity - ? WHERE product_id = ?";
            PreparedStatement pstUpdate = con.prepareStatement(updateSQL);
            pstUpdate.setInt(1, qty);
            pstUpdate.setInt(2, productId);
            pstUpdate.executeUpdate();

            // Append item to bill
            bill.append(name).append(" x").append(qty).append(" = Rs.").append(subtotal).append("\n");
        }

        con.commit();

        // Append total and date to bill
        bill.append("------------------\n");
        bill.append("Total: Rs.").append(totalAmount).append("\n");
        bill.append("Date: ").append(java.time.LocalDate.now());

        // Show bill in JTextArea
        jTextArea1.setText(bill.toString());

        JOptionPane.showMessageDialog(this, "Sale Completed!");

        // Clear cart
        model.setRowCount(0);
        totalAmount = 0;
        lblTotal.setText("Total: Rs.0");

    } catch (Exception e) {
        try { if (con != null) con.rollback(); } catch (Exception ex) {}
        e.printStackTrace();  // See exact error in console
        JOptionPane.showMessageDialog(this, "Error completing sale! Check console for details.");
    }
    }//GEN-LAST:event_btnCompleteActionPerformed

    private void loadProducts() {

    try {
        Connection con = DBConnection.getConnection();
        String sql = "SELECT * FROM products";
        PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();

        cmbProducts.removeAllItems();

        while(rs.next()){
            cmbProducts.addItem(
                rs.getInt("product_id") + " - " +
                rs.getString("product_name") + " - Rs." +
                rs.getDouble("unit_price")
            );
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
private void generateBill() {
        DefaultTableModel model = (DefaultTableModel) tblCart.getModel();
        StringBuilder bill = new StringBuilder();
        bill.append("------ BILL ------\n");
        for (int i = 0; i < model.getRowCount(); i++) {
            String name = model.getValueAt(i, 1).toString();
            String qty = model.getValueAt(i, 3).toString();
            String subtotal = model.getValueAt(i, 4).toString();
            bill.append(name).append(" x").append(qty).append(" = Rs.").append(subtotal).append("\n");
        }
        bill.append("------------------\n");
        bill.append("Total: Rs.").append(totalAmount).append("\n");
        bill.append("Date: ").append(java.time.LocalDate.now());
        JOptionPane.showMessageDialog(this, bill.toString());
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SalesForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JButton btnComplete;
    private javax.swing.JComboBox<String> cmbProducts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblCart;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables
}
